apiVersion: v2
description: A Helm chart to run the Fairwinds Insights agent
name: insights-agent
version: 5.23.1
appVersion: 9.2.1
kubeVersion: ">= 1.22.0-0"
icon: https://raw.githubusercontent.com/FairwindsOps/charts/master/stable/insights-agent/icon.png
maintainers:
  - name: vitorvezani
  - name: jdesouza
dependencies:
  - name: goldilocks
    repository: https://charts.fairwinds.com/stable
    version: '10.4.*'
    condition: goldilocks.enabled
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: '29.14.*'
    condition: prometheus-metrics.installPrometheusServer
  - name: insights-admission
    repository: https://charts.fairwinds.com/stable
    version: '1.12.*'
    condition: admission.enabled
  - name: falco
    repository: https://falcosecurity.github.io/charts
    version: '9.1.*'
    condition: falco.installFalco
    alias: falcosecurity
  - name: vpa
    version: '4.12.*'
    repository: https://charts.fairwinds.com/stable
    condition: right-sizer.enableClosedBeta
    alias: right-sizer-vpa
  - name: trivy
    version: 0.24.0
    repository: https://aquasecurity.github.io/helm-charts/
    condition: trivy.server.installTrivyServer
    alias: trivy-server
  - name: dcgm-exporter
    version: '4.8.2'
    repository: https://nvidia.github.io/dcgm-exporter/helm-charts
    condition: dcgm-exporter.enabled
  - name: device-metrics-exporter-charts
    version: 'v1.5.0'
    repository: https://rocm.github.io/device-metrics-exporter
    condition: amd-device-metrics-exporter.enabled
    alias: amd-device-metrics-exporter
