apiVersion: v2
name: datadog-apm
description: A modified chart that only installs the datadog-apm agent
type: application
version: 2.1.0
appVersion: "7.81.1"
maintainers:
  - name: sudermanjr
  - name: Azahorscak
