{{ range $name, $options := .Values.cronjobs }}
{{ if $options.schedule }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "fairwinds-insights.fullname" $ }}-cj-{{ $name }}
  labels:
    {{- include "fairwinds-insights.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cronjob-{{ $name }}
spec:
  schedule: "{{ $options.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ dig "successfulJobsHistoryLimit" $.Values.cronjobOptions.successfulJobsHistoryLimit $options }}
  failedJobsHistoryLimit: {{ dig "failedJobsHistoryLimit" $.Values.cronjobOptions.failedJobsHistoryLimit $options }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          {{- include "fairwinds-insights.imagePullSecrets" $ | nindent 10 }}
          serviceAccountName: {{ include "fairwinds-insights.fullname" $ }}-cronjob-executor
          containers:
            - name: {{ $name }}
              image: "{{ $.Values.cronjobImage.repository }}:{{ include "fairwinds-insights.cronjobImageTag" $ }}"
              command: ["{{ $options.command }}"]
              args:
              {{- with $options.interval }}
                - --interval={{ . }}
              {{- end }}
              {{- include "env" (dict "useReadReplica" $options.useReadReplica "useMigrationCredentials" (dig "useMigrationCredentials" false $options) "root" $) | indent 14 }}
              {{- $envVars := concat (default list $.Values.cronjobOptions.additionalEnvVars) ($options.additionalEnvVars | default list) }}
              {{- with $envVars }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
              imagePullPolicy: Always
              resources:
                {{- toYaml (default $.Values.cronjobOptions.resources $options.resources) | nindent 16 }}
              {{- $githubSecret := $options.githubSecret | default dict }}
              {{- $githubSecretEnabled := or $options.includeGitHubSecret ($githubSecret.enabled | default false) }}
              {{- $githubSecretName := $githubSecret.name | default "github-secrets" }}
              {{- if $githubSecretEnabled }}
              volumeMounts:
              - name: secrets
                mountPath: /var/run/secrets/github
              {{- end }}
              securityContext:
                {{- toYaml (default $.Values.cronjobOptions.securityContext $options.securityContext) | nindent 16 }}
          {{- if $githubSecretEnabled }}
          volumes:
            - name: secrets
              secret:
                secretName: {{ $githubSecretName }}
                optional: true
          {{- end }}
---
{{ end }}
{{ end }}
