{{- if and (not .Values.postgresql.ephemeral) .Values.postgresql.auth.externalSecret.enabled }}
{{- $es := .Values.postgresql.auth.externalSecret }}
{{- $vault := $es.vault }}
{{- $path := $vault.path }}
{{- $pgProp := $vault.postgresqlPasswordProperty }}
{{- $temporalProp := coalesce $vault.temporalPasswordProperty $pgProp }}
apiVersion: {{ $es.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  labels:
    {{- include "fairwinds-insights.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ $es.refreshInterval | quote }}
  secretStoreRef:
    name: {{ $es.secretStoreRef.name }}
    kind: {{ $es.secretStoreRef.kind }}
  target:
    name: {{ .Values.postgresql.auth.existingSecret }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: {{ $path | quote }}
        property: {{ $pgProp | quote }}
    - secretKey: password
      remoteRef:
        key: {{ $path | quote }}
        property: {{ $temporalProp | quote }}
    - secretKey: readonly-password
      remoteRef:
        key: {{ $path | quote }}
        property: {{ $vault.readonlyPasswordProperty | quote }}
    - secretKey: timescale-password
      remoteRef:
        key: {{ $path | quote }}
        property: {{ $vault.timescalePasswordProperty | quote }}
{{- end }}
