{{- if .Values.options.autogenerateKeys }}
apiVersion: v1
data:
    COOKIE_HASH_KEY: {{ randAlphaNum 64 | b64enc }}
    COOKIE_BLOCK_KEY: {{ randAlphaNum 32 | b64enc }}
    SESSION_AUTH_KEY: {{ randAlphaNum 64 | b64enc }}
    SESSION_ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc }}
    AES_BASE64_CYPHER_KEY: {{ default (randAlphaNum 32) .Values.encryption.aes.cypherKey | b64enc }}
kind: Secret
metadata:
    name: {{ .Values.options.secretName }}
type: Opaque
{{- end }}
---
{{- if .Values.postgresql.ephemeral }}
{{- $password := default (randAlphaNum 32) .Values.postgresql.auth.password }}
{{- $migrationPassword := default $password .Values.postgresql.auth.migrationPassword }}
apiVersion: v1
data:
    password: {{ b64enc $password }}
    postgresql-password: {{ b64enc $password }}
    username: {{ b64enc (include "fairwinds-insights.postgresqlAppUsername" .) }}
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
type: Opaque
{{- if eq (include "fairwinds-insights.postgresqlSplitAppMigration" .) "true" }}
---
apiVersion: v1
data:
    password: {{ b64enc $migrationPassword }}
    postgresql-password: {{ b64enc $migrationPassword }}
    username: {{ b64enc (include "fairwinds-insights.postgresqlMigrationUsername" .) }}
kind: Secret
metadata:
  name: {{ include "fairwinds-insights.postgresqlMigrationSecret" . }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
type: Opaque
{{- end }}
---
apiVersion: v1
data:
    username: {{ b64enc "postgres" }}
    password: {{ b64enc (default (randAlphaNum 32) .Values.postgresql.auth.superuserpassword) }}
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSuperUserSecret }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
type: Opaque
{{- end }}
---
{{- if .Values.timescale.ephemeral }}
{{- $tsPassword := default (randAlphaNum 32) .Values.timescale.password }}
{{- $tsMigrationPassword := default $tsPassword .Values.timescale.auth.migrationPassword }}
apiVersion: v1
data:
    password: {{ b64enc $tsPassword }}
    postgresql-password: {{ b64enc $tsPassword }}
    username: {{ b64enc (include "fairwinds-insights.timescaleAppUsername" .) }}
kind: Secret
metadata:
  name: {{ .Values.timescale.auth.existingSecret }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/resource-policy": keep
type: Opaque
{{- if eq (include "fairwinds-insights.timescaleSplitAppMigration" .) "true" }}
---
apiVersion: v1
data:
    password: {{ b64enc $tsMigrationPassword }}
    postgresql-password: {{ b64enc $tsMigrationPassword }}
    username: {{ b64enc (include "fairwinds-insights.timescaleMigrationUsername" .) }}
kind: Secret
metadata:
  name: {{ include "fairwinds-insights.timescaleMigrationSecret" . }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/resource-policy": keep
type: Opaque
{{- end }}
---
apiVersion: v1
data:
    username: {{ b64enc "postgres" }}
    password: {{ b64enc (default (randAlphaNum 32) .Values.timescale.superuserpassword) }}
kind: Secret
metadata:
  name: {{ .Values.timescale.auth.existingSuperUserSecret }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
type: Opaque
{{- end }}
---
{{- if .Values.timescale.ephemeral }}
apiVersion: v1
kind: Secret
metadata:
  name: fwinsights-timescale-ca
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/tls
{{ $ca := genCA "timescale" 1826 -}}
stringData:
    tls.crt: {{ $ca.Cert | quote }}
    tls.key: {{ $ca.Key  | quote }}
{{- end }}
---
{{- if .Values.postgresql.ephemeral }}
apiVersion: v1
kind: Secret
metadata:
  name: fwinsights-postgresql-ca
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/tls
{{ $ca := genCA "postgres" 1826 -}}
stringData:
    tls.crt: {{ $ca.Cert | quote }}
    tls.key: {{ $ca.Key  | quote }}
{{- end }}
---
